ggplot_rc = \
{
"patch.linewidth" : 0.5,
"patch.facecolor" : '#348ABD',
"patch.edgecolor" : '#EEEEEE',
"patch.antialiased" : True,
"font.size" : 10.0,
"axes.facecolor" : '#E5E5E5',
"axes.edgecolor" : 'white',
"axes.linewidth" : 2,
"axes.grid" : True,
"axes.titlesize" : 'x-large',
"axes.labelsize" : 'large',
"axes.labelcolor" : '#555555',
"axes.axisbelow" : True,
"axes.color_cycle" : ['#0072B2','#D55E00','#CC79A7','#009E73', '#E69F00',
				      '#F0E442', '#56B4E9'],
"xtick.color" : '#555555',
"xtick.direction" : 'out',
"ytick.color" : '#555555',
"ytick.direction" : 'out',
"grid.color" : 'white',
"grid.linestyle" : '-',
"figure.facecolor" : 'white',
"figure.edgecolor" : '0.50',
}
