#!/usr/bin/python

'''Look up the metadata generated by an analysis, or write it back out if it's changed. 

'''

import xml.etree.ElementTree as etree
import sys
from matplotlib.mlab import csv



__author__ = "Chloe Lewis"
__copyright__ = "Copyright 2012, Regents of the University of California"
__credits__ = []
__license__ = None
__version__ = "0.5"
__maintainer__ = "Chloe Lewis"
__email__ = "chlewis@berkeley.edu"
__status__ = "Development"


class Metadata:
    '''Metadata values for any analysis. Metadata is intrinsic to a dataset, and is stored using Ecological Markup Language. %citation TODO.'''

    def __init__(self, datapath, asklist):
        ''' Reads the metadata values requested in asklist from the EML file sibling to datapath (same location, same filename, .XML extension).'''

        assert type(asklist) == type(())
        xmlfile = datapath.split('.')[-2] + '.xml'
        print xmlfile
        try:
            xf = open(xmlfile,'r')
        except IOError:
            print 'IOError: Could not open %s'%xmlfile

        # Dumb beginner version: just a string reader

             
        reader = csv.reader(xf)
 
        self.data = {}
        for line in reader:
            self.data[line[0]] = line[1]

        

        

        

        

        
